### ISSUE TITLE
create new release

### ISSUE THREAD

**Issue by DanielRuf** [evanderkoogh/node-sitemap-stream-parser#6]
So far there is no new release for about 2 years.

**Comment by evanderkoogh** [comment]
Nope.. I haven't had a need for any new functionality. If you have anything you are looking for please let me know and I can see what I can do?

**Comment by DanielRuf** [comment]
What about https://github.com/evanderkoogh/node-sitemap-stream-parser/commit/03567b051395f3a0a991a0ddedcfd4c85347bbe3 which would be at least a minor version change.

**Comment by evanderkoogh** [comment]
Hmm.. you are right. I was convinced I had released that. So I just released 1.3.0

Thanks for pinging me. And let me know if you need anything else. I do not currently need it anything more for my own work, but more than happy to take new feature requests and/or PRs.

**Comment by DanielRuf** [comment]
Great, thanks for the new release.
